/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-06-15")
public class PrefetchInputSplits implements org.apache.thrift.TBase<PrefetchInputSplits, PrefetchInputSplits._Fields>, java.io.Serializable, Cloneable, Comparable<PrefetchInputSplits> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PrefetchInputSplits");

  private static final org.apache.thrift.protocol.TField SPLITS_FIELD_DESC = new org.apache.thrift.protocol.TField("splits", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PrefetchInputSplitsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PrefetchInputSplitsTupleSchemeFactory());
  }

  private List<Split> splits; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SPLITS((short)1, "splits");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SPLITS
          return SPLITS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SPLITS, new org.apache.thrift.meta_data.FieldMetaData("splits", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "Split"))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PrefetchInputSplits.class, metaDataMap);
  }

  public PrefetchInputSplits() {
  }

  public PrefetchInputSplits(
    List<Split> splits)
  {
    this();
    this.splits = splits;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PrefetchInputSplits(PrefetchInputSplits other) {
    if (other.isSetSplits()) {
      List<Split> __this__splits = new ArrayList<Split>(other.splits.size());
      for (Split other_element : other.splits) {
        __this__splits.add(other_element);
      }
      this.splits = __this__splits;
    }
  }

  public PrefetchInputSplits deepCopy() {
    return new PrefetchInputSplits(this);
  }

  @Override
  public void clear() {
    this.splits = null;
  }

  public int getSplitsSize() {
    return (this.splits == null) ? 0 : this.splits.size();
  }

  public java.util.Iterator<Split> getSplitsIterator() {
    return (this.splits == null) ? null : this.splits.iterator();
  }

  public void addToSplits(Split elem) {
    if (this.splits == null) {
      this.splits = new ArrayList<Split>();
    }
    this.splits.add(elem);
  }

  public List<Split> getSplits() {
    return this.splits;
  }

  public PrefetchInputSplits setSplits(List<Split> splits) {
    this.splits = splits;
    return this;
  }

  public void unsetSplits() {
    this.splits = null;
  }

  /** Returns true if field splits is set (has been assigned a value) and false otherwise */
  public boolean isSetSplits() {
    return this.splits != null;
  }

  public void setSplitsIsSet(boolean value) {
    if (!value) {
      this.splits = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SPLITS:
      if (value == null) {
        unsetSplits();
      } else {
        setSplits((List<Split>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SPLITS:
      return getSplits();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SPLITS:
      return isSetSplits();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PrefetchInputSplits)
      return this.equals((PrefetchInputSplits)that);
    return false;
  }

  public boolean equals(PrefetchInputSplits that) {
    if (that == null)
      return false;

    boolean this_present_splits = true && this.isSetSplits();
    boolean that_present_splits = true && that.isSetSplits();
    if (this_present_splits || that_present_splits) {
      if (!(this_present_splits && that_present_splits))
        return false;
      if (!this.splits.equals(that.splits))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_splits = true && (isSetSplits());
    list.add(present_splits);
    if (present_splits)
      list.add(splits);

    return list.hashCode();
  }

  @Override
  public int compareTo(PrefetchInputSplits other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSplits()).compareTo(other.isSetSplits());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSplits()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.splits, other.splits);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PrefetchInputSplits(");
    boolean first = true;

    sb.append("splits:");
    if (this.splits == null) {
      sb.append("null");
    } else {
      sb.append(this.splits);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PrefetchInputSplitsStandardSchemeFactory implements SchemeFactory {
    public PrefetchInputSplitsStandardScheme getScheme() {
      return new PrefetchInputSplitsStandardScheme();
    }
  }

  private static class PrefetchInputSplitsStandardScheme extends StandardScheme<PrefetchInputSplits> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PrefetchInputSplits struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SPLITS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list58 = iprot.readListBegin();
                struct.splits = new ArrayList<Split>(_list58.size);
                Split _elem59;
                for (int _i60 = 0; _i60 < _list58.size; ++_i60)
                {
                  _elem59 = new Split();
                  _elem59.read(iprot);
                  struct.splits.add(_elem59);
                }
                iprot.readListEnd();
              }
              struct.setSplitsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PrefetchInputSplits struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.splits != null) {
        oprot.writeFieldBegin(SPLITS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.splits.size()));
          for (Split _iter61 : struct.splits)
          {
            _iter61.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PrefetchInputSplitsTupleSchemeFactory implements SchemeFactory {
    public PrefetchInputSplitsTupleScheme getScheme() {
      return new PrefetchInputSplitsTupleScheme();
    }
  }

  private static class PrefetchInputSplitsTupleScheme extends TupleScheme<PrefetchInputSplits> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PrefetchInputSplits struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSplits()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetSplits()) {
        {
          oprot.writeI32(struct.splits.size());
          for (Split _iter62 : struct.splits)
          {
            _iter62.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PrefetchInputSplits struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list63 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.splits = new ArrayList<Split>(_list63.size);
          Split _elem64;
          for (int _i65 = 0; _i65 < _list63.size; ++_i65)
          {
            _elem64 = new Split();
            _elem64.read(iprot);
            struct.splits.add(_elem64);
          }
        }
        struct.setSplitsIsSet(true);
      }
    }
  }

}

